Controllers/ViewControllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Last_Project.ViewModels.Pages;
using Web_Last_Project.ViewModels.Pages.Data.Resources;
using Web_Last_Project.ViewModels.Tools;
using System.Diagnostics;
using System.IO;
using Web_Last_Project.ViewModels.Pages.Data.BlogTools;

namespace Web_Last_Project.Controllers.ViewControllers
{
    public class BlogController : Controller
    {
        private readonly IWebHostEnvironment _appEnvironment;

        public BlogController(IWebHostEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Blog);
            ViewBag.Blog = PageProvider.GetPage(NamePage.BlogListCards).GetFullCards();

            return View();
        }

        public IActionResult Card(int id)
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Blog);
            ViewBag.Blog = PageProvider.GetPage(NamePage.BlogListCards).FaindCard(id);

            return View();
        }

        public IActionResult Editable()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Blog);

            ViewBag.Blog = PageProvider.GetPage(NamePage.BlogListCards).GetFullCards();

            return View();

        }


        public IActionResult Change(int id)
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Blog);
            ViewBag.Blog = PageProvider.GetPage(NamePage.BlogListCards).FaindCard(id);

            ViewBag.CardID = id.ToString();

            return View();

        }

        public IActionResult Add()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Blog);

            return View();
        }

        [HttpPost]
        public string Set([FromBody] BigCard bigCard)
        {
            BlogCardData blogtCard = PageProvider.GetPage(NamePage.NewBlogCard);

            blogtCard.Data = bigCard;

            string file = bigCard.file;

            string path = _appEnvironment.WebRootPath + $"/Blog/img/";

            try
            {
                blogtCard.Save();

                if (blogtCard.isSave == true)
                {
                    WorkingPicture.AddPicture(file, path, blogtCard.Data.Alt);
                }
                else
                {
                    return "fail";
                }

                return "successfully";
            }
            catch (Exception ex)
            {

                Debug.WriteLine(ex);

                return "fail";
            }

        }

        [HttpDelete]
        public string Delete(int id)
        {
            BlogCardData blogCard = PageProvider.GetPage(NamePage.BlogListCards).FaindCard(id);

            string path = _appEnvironment.WebRootPath + $"/Blog/img/";

            try
            {
                WorkingPicture.RemovePicture(path, blogCard.Data.Alt);

                blogCard.DeleteCard();

                return "successfully";
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);

                return "fail";
            }
        }

        [HttpPut]
        public string Edit([FromBody] BigCard Card)
        {
            BlogCardData blogCard;

            try
            {
                blogCard = PageProvider.GetPage(NamePage.BlogListCards).FaindCard(Convert.ToInt32(Card.Alt));
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);

                return "fail";
            }

            Card.Alt = blogCard.Data.Alt;

            string file = Card.file;
            string path = _appEnvironment.WebRootPath + $"/Blog/img/";

            blogCard.Data = Card;

            try
            {
                blogCard.Save();

                if (file != null && file != string.Empty && file.Length > 100)
                {
                    if (blogCard.isSave == true)
                    {
                        WorkingPicture.EditPicture(file, path);
                    }
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);

                return "fail";
            }


            return "successfully";
        }
    }
}

Controllers/ViewControllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Last_Project.ViewModels.Pages;

namespace Web_Last_Project.Controllers.ViewControllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Contacts);

            ViewBag.ContactsMain = PageProvider.GetPage(NamePage.ContactsMain);

            return View();
        }
    }
}

Controllers/ViewControllers/HeadingController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Last_Project.ViewModels.Pages.Data.Resources;
using Web_Last_Project.ViewModels.Pages.Data;
using Web_Last_Project.ViewModels.Pages;
using Web_Last_Project.ViewModels.Tools;
using System.Diagnostics;

namespace Web_Last_Project.Controllers.ViewControllers
{
    public class HeadingController : Controller
    {
        private readonly IWebHostEnvironment _appEnvironment;

        public HeadingController(IWebHostEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Heading);

            return View();
        }

        public IActionResult Change()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Heading);

            return View();
        }

        [HttpPut]
        public string Set([FromBody] HeadingAndFooter packageHeading)
        {

            string path = _appEnvironment.WebRootPath + $"/Layout/img/";

            try
            {
                if (packageHeading.file != null && packageHeading.file != string.Empty)
                {
                    WorkingPicture.EditPicture(packageHeading.file, path);
                }

                HeaderData header = PageProvider.GetPage(NamePage.BaseHeader);

                header.Data = packageHeading;
                header.Save();

                return "successfully";
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);

                return "fail";
            }

        }
    }
}

Controllers/ViewControllers/HeroController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Last_Project.ViewModels.Pages;
using Web_Last_Project.ViewModels.Pages.Data.Resources;
using Web_Last_Project.ViewModels.Pages.Data;
using Web_Last_Project.ViewModels.Tools.DeliverymanHero;
using Web_Last_Project.ViewModels.Tools;
using System.Diagnostics;

namespace Web_Last_Project.Controllers.ViewControllers
{
    public class HeroController : Controller
    {
        private readonly IWebHostEnvironment _appEnvironment;

        public HeroController(IWebHostEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
        }

        public IActionResult Index()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Hero);

            ViewBag.Hero = PageProvider.GetPage(NamePage.Hero);

            return View();
        }

        public IActionResult IndexAdmin()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Hero);

            ViewBag.Hero = PageProvider.GetPage(NamePage.Hero);

            return View();
        }

        public IActionResult Update()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Hero);

            ViewBag.Hero = PageProvider.GetPage(NamePage.Hero);

            return View();
        }

        public IActionResult Add()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Hero);

            return View();
        }

        [HttpPost]
        public string Set([FromBody] HeroSlide package)
        {
            HeroData heroData = PageProvider.GetPage(NamePage.BaseHero);

            string path = _appEnvironment.WebRootPath + $"/Hero/img/slides-img/";

            heroData.AddSlogan(package.slideText);

            try
            {
                heroData.Save();

                WorkingPicture.AddPicture(package.fileBit, path);

                return "successfully";
            }
            catch (Exception ex)
            {

                Debug.WriteLine(ex);

                return "fail";
            }
        }

        [HttpPut]
        public string Update([FromBody] Hero packageHero)
        {
            HeroData heroData = PageProvider.GetPage(NamePage.BaseHero);

            string path = _appEnvironment.WebRootPath + $"/Hero/img/slides-img/";

            try
            {
                for (int i = 0; i < packageHero.files.Length; i++)
                {

                    if (packageHero.files[i].Length > 5)
                    {
                        WorkingPicture.EditPicture(packageHero.files[i], path);
                    }
                    else
                    {
                        int number = Convert.ToInt32(packageHero.files[i]);

                        string fileName = heroData.Data.Slogans[number];

                        if (fileName.Length > 8)
                        {
                            fileName = fileName.Substring(0, 8);
                        }

                        WorkingPicture.RemovePicture(path, fileName);
                    }
                }

                heroData.Data = packageHero;
                heroData.Save();

                return "successfully";
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);

                return "fail";
            }
        }
    }
}

Views/Shared/Mistake.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/normalize.css">
    <link rel="stylesheet" href="~/mistake_style_data/css/style1.css">
    <title>Сервис недоступен</title>
</head>

<body>
    <div class="container">
        <img src="~/mistake_style_data/img/mistake_img.png" alt="перекрытая дорога" class="img">
        <div class="box">
            <h1 class="title">
                Упс.... Кажется,&nbsp;что-&nbsp;то&nbsp;пошло&nbsp;не&nbsp;так.
            </h1>
            <p class="text">
                Приносим свои извенения, сервис временно&nbsp;недоступен.
            </p>
        </div>
    </div>
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/General/css/normalize.css">
    <link rel="stylesheet" href="~/General/css/Style8.css">
    <link rel="stylesheet" href="~/Layout/css/Style4.css">
    
</head>


<body>
    <header class="header" id="header">
        <div class="container">
            <a href="#" class="logo header__logo">
                <img class="header__logo__img" src="~/Layout/img/@ViewBag.Container.Logo" alt="логотип кампании @ViewBag.Container.Data.CompanyName">
            </a>
            <nav class="header__nav">
                <ul class="header__list list-reset">
                    <li class="header__list__item">
                        <a  asp-controller="Home" asp-action="Admin" class="header__link">
                            Админ
                        </a>
                    </li>
                    <li class="header__list__item">
                        <a href="~/Home/Index#"  class="header__link">
                            @ViewBag.Container.Data.HeadingMenu[0]
                        </a>
                    </li>
                    <li class="header__list__item">
                        <a href="~/Home/Index#projects"  class="header__link">
                            @ViewBag.Container.Data.HeadingMenu[1]
                        </a>
                    </li>
                    <li class="header__list__item">
                        <a href="~/Home/Index#services" class="header__link">
                            @ViewBag.Container.Data.HeadingMenu[2]
                        </a>
                    </li>
                    <li class="header__list__item">
                        <a href="~/Home/Index#blog"  class="header__link">
                            @ViewBag.Container.Data.HeadingMenu[3]
                        </a>
                    </li>
                    <li class="header__list__item">
                        <a  href="~/Home/Index#contacts" class="header__link">
                            @ViewBag.Container.Data.HeadingMenu[4]
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer class="footer">
        <div class="container">
            <span class="footer__span">
                @ViewBag.Container.Data.Footer
            </span>
        </div>   
    </footer>
  </body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/General/css/normalize.css">
    <link rel="stylesheet" href="~/General/css/Style8.css">
    <link rel="stylesheet" href="~/Layout/css/adminStyle1.css">
</head>

<body>
    <header class="header" id="header">
        <button aria-label="Меню навигации" class="burger burger--active  header__burger button-reset">
            <span class="burger__span"></span>
            <span class="burger__span"></span>
            <span class="burger__span"></span>
        </button>
        <span class="header__span">
            Admin:
        </span>
        <p class="header__text">
            Adfwewefwefwe
        </p>
        <a href="/Home/Admin" class="header__link">
            Выход
        </a>
    </header>
    <nav class="sidenav sidenav--active" id="mainNav">
        <ul class="sidenav__list list-reset">
            <li class="sidenav__item">
                <a class="sidenav__link "   href="#">РАБОЧИЙ СТОЛ</a>
            </li>
            <li class="sidenav__item">                            
                @if (ViewBag.MenuSelect == "heading")
                {
                    <a class="sidenav__link sidenav__link--active" asp-controller="Heading" asp-action="Index">ЗАГОЛОВОК</a>
                }
                else
                {
                    <a class="sidenav__link" asp-controller="Heading" asp-action="Index">ЗАГОЛОВОК</a>
                }
            </li>
            <li class="sidenav__item">
                @if (ViewBag.MenuSelect == "hero")
                {
                    <a class="sidenav__link sidenav__link--active" asp-controller="Hero" asp-action="IndexAdmin">
                        @ViewBag.Container.Data.HeadingMenu[0]
                    </a>
                }
                else
                {
                    <a class="sidenav__link" asp-controller="Hero" asp-action="IndexAdmin">
                        @ViewBag.Container.Data.HeadingMenu[0]
                    </a>
                }
            </li>
            <li class="sidenav__item"> 
                @if (ViewBag.MenuSelect == "project")
                {
                    <a class="sidenav__link sidenav__link--active" asp-controller="Projects" asp-action="Index">
                        @ViewBag.Container.Data.HeadingMenu[1]
                    </a>
                }
                else
                {
                    <a class="sidenav__link" asp-controller="Projects" asp-action="Index">
                        @ViewBag.Container.Data.HeadingMenu[1]
                    </a>
                }
            </li>
            <li class="sidenav__item">       
                @if (ViewBag.MenuSelect == "services")
                {
                    <a class="sidenav__link sidenav__link--active" asp-controller="Services" asp-action="Index">
                        @ViewBag.Container.Data.HeadingMenu[2]
                    </a>
                }
                else
                {
                    <a class="sidenav__link" asp-controller="Services" asp-action="Index">
                        @ViewBag.Container.Data.HeadingMenu[2]
                    </a>
                }
            </li>
            <li class="sidenav__item"> 
                @if (ViewBag.MenuSelect == "blog")
                {
                    <a class="sidenav__link sidenav__link--active" asp-controller="Blog" asp-action="Index">
                        @ViewBag.Container.Data.HeadingMenu[3]
                    </a>
                }
                else
                {
                    <a class="sidenav__link" asp-controller="Blog" asp-action="Index">
                        @ViewBag.Container.Data.HeadingMenu[3]
                    </a>
                }
            </li>
            <li class="sidenav__item">
                @if (ViewBag.MenuSelect == "contacts")
                {
                    <a class="sidenav__link sidenav__link--active" asp-controller="Contacts" asp-action="Index">
                        @ViewBag.Container.Data.HeadingMenu[4]
                    </a>
                }
                else
                {
                    <a class="sidenav__link" asp-controller="Contacts" asp-action="Index">
                        @ViewBag.Container.Data.HeadingMenu[4]
                    </a>
                }
            </li>
        </ul>
    </nav>
    <main class="main main--active">
        @RenderBody()
    </main>


    <script src="~/Layout/js/AdminScript6.js"></script>
</body>
</html>