Controllers/ViewControllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Last_Project.ViewModels.Pages;
using Web_Last_Project.ViewModels.Pages.Data.Resources;
using System;
using System.Diagnostics;
using Web_Last_Project.ViewModels.Pages.Data.ServicesTools;

namespace Web_Last_Project.Controllers.ViewControllers
{
    public class ServicesController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Services);

            ViewBag.Services = PageProvider.GetPage(NamePage.Services);

            return View();
        }


        public IActionResult Change()
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Services);

            ViewBag.Services = PageProvider.GetPage(NamePage.Services);

            return View();
        }

        public IActionResult Add(int count)
        {
            ViewBag.MenuSelect = ChackAdmin.IsSelectedMenuItem(Menu.Services);

            if (count == -1)
            {
                ViewBag.ServicesItem = new LitleCard();

                return View();
            }
            else
            {
                ViewBag.ServicesItem = PageProvider.GetPage(NamePage.Services).ServicesPage[count].Data;

                return View();
            }

        }

        [HttpPost]
        public string Set([FromBody] LitleCard service)
        {
            ServicesData serviceData = PageProvider.GetPage(NamePage.NewServices);

            serviceData.Data = service;

            try
            {
                serviceData.Save();

                return "successfully";
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);

                return "fail";
            }
        }

        [HttpPut]
        public string Edit([FromBody] LitleCard service)
        {
            ServicesList services = PageProvider.GetPage(NamePage.Services);

            string[] str = service.Title.Split('*');

            service.Title = str[0];

            int index = Convert.ToInt32(str[1]);         

            ServicesData serviceData = PageProvider.GetPage(NamePage.NewServices);

            serviceData.Data = service;

            try
            {
                services.Delete(index);

                serviceData.Save();

                return "successfully";
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);

                return "fail";
            }      
        }

        [HttpDelete]
        public string Delete(int index)
        {
            ServicesList Services = PageProvider.GetPage(NamePage.Services);

            try
            {
                Services.Delete(index);

                return "successfully";
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);

                return "fail";
            }

        }
    }
}

Views/Services/Add.cshtml
@{
    Layout = "_layoutAdmin";
    ViewData["title"] = "Добовление";
}

<link rel="stylesheet" href="~/General/css/StyleLayoutSumbit.css">
<link rel="stylesheet" href="~/Services/css/StyleAdd3.css">

<form class="form--services" id="Form-services" method="post">
    <section class="services section" id="services">
        <div class="container">
            <label for="textTitle" class="form__services__label labal--title">
                <span class="form__services__text">
                    Заголовок:
                </span>
                <input type="text" id="textTitle" value="@ViewBag.ServicesItem.Title" name="textTitle" class="form__services__input input--text input--title">
            </label>
            <label for="textDescrit" class="form__services__label labal--descrit">
                <span class="form__services__text">
                    Текст:
                </span>
                <textarea rows="25" id="textDescrit" name="textDescrit" 
                          class="form__services__input input--text input--descrit">@ViewBag.ServicesItem.Description</textarea>
            </label>
        </div>
    </section>
    <section class="layout-submit moving-update">
        <div class="container">
            <a asp-controller="Services" asp-action="Change" class="button-moving-update link-btn">
                Назад
            </a>
            <button type="submit" class="button-moving-update link-btn button-reset">
                Добавить
            </button>
        </div>
    </section>
</form>

<script src="~/General/libs/JustValidate/just-validate.production.min.js"></script>
<script src="~/General/libs/jquery.min.js"></script>
<script src="~/Services/js/ScriptAdd2.js"></script>

@if (ViewBag.ServicesItem.Title == string.Empty || ViewBag.ServicesItem.Title == null)
{
    <script src="~/Services/js/ScriptPost2.js"></script>
}
else
{
    <script src="~/Services/js/ScriptPut4.js"></script>
}

Views/Services/Change.cshtml
@{
    Layout = "_layoutAdmin";

    ViewData["title"] = @ViewBag.Container.Data.HeadingMenu[2];
}

<link rel="stylesheet" href="~/General/css/StyleInfo5.css">
<link rel="stylesheet" href="~/General/css/StyleLayoutSumbit.css">
<link rel="stylesheet" href="~/Services/css/StyleChange1.css">

<section class="services" id="services">
    <div class="container">
        <ul class="services__list list-reset">
            @for (int i = 0; i < ViewBag.Services.ServicesPage.Length; i++)
            {
                <li class="services__list__item">
                    <div class="services__button accordion">
                        <svg class="arrow-bottom" viewBox="0 0 9 14">
                            <path class="svg-arrow"
                                  d="M6.660,8.922 L6.660,8.922 L2.350,13.408 L0.503,11.486 L4.813,7.000 L0.503,2.515 L2.350,0.592 L8.507,7.000 L6.660,8.922 Z" />
                        </svg>
                        <span class="services__span">
                            @ViewBag.Services.ServicesPage[i].Data.Title
                        </span>
                    </div>
                    <ul class="services__btn-list list-reset">
                        <li class="services__btn-list__item">
                            <abbr data-title="Изменить" class="button-info">
                            <a class="services__btn" href="./Add?count=@i">
                                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M18.3785 8.44975L11.4637 15.3647C11.1845 15.6439 10.8289 15.8342 10.4417 15.9117L7.49994 16.5L8.08829 13.5582C8.16572 13.1711 8.35603 12.8155 8.63522 12.5363L15.5501 5.62132M18.3785 8.44975L19.7927 7.03553C20.1832 6.64501 20.1832 6.01184 19.7927 5.62132L18.3785 4.20711C17.988 3.81658 17.3548 3.81658 16.9643 4.20711L15.5501 5.62132M18.3785 8.44975L15.5501 5.62132"
                                          stroke="#000000" stroke-width="2" stroke-linecap="round"
                                          stroke-linejoin="round" />
                                    <path d="M5 20H19" stroke-width="2" stroke-linecap="round"
                                          stroke-linejoin="round" />
                                </svg>
                              
                            </a>
                            </abbr>
                        </li>
                        <li class="services__btn-list__item">
                            <abbr data-title="Удалить" class="services__btn button-info" onclick="RemoveSlade(this.parentNode.parentNode.parentNode, @i)">
                                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M10 11V17" stroke-width="2" stroke-linecap="round"
                                          stroke-linejoin="round" />
                                    <path d="M14 11V17" stroke-width="2" stroke-linecap="round"
                                          stroke-linejoin="round" />
                                    <path d="M4 7H20" stroke-width="2" stroke-linecap="round"
                                          stroke-linejoin="round" />
                                    <path d="M6 7H12H18V18C18 19.6569 16.6569 21 15 21H9C7.34315 21 6 19.6569 6 18V7Z"
                                          stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                    <path d="M9 5C9 3.89543 9.89543 3 11 3H13C14.1046 3 15 3.89543 15 5V7H9V5Z"
                                          stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                            </abbr>                       
                        </li>
                    </ul>
                </li>
            }
        </ul>
    </div>
</section>
<section class="layout-submit">
    <div class="container">
        <a asp-controller="Services" asp-action="Index" class="button-moving-update link-btn">
            Назад
        </a>
        <a href="./Add?count=-1" class="button-moving-update link-btn">
                Добавить сервис
        </a>
    </div>
</section>

<script src="~/General/libs/jquery.min.js"></script>
<script src="~/Services/js/ScriptChange2.js"></script>
                             

Views/Services/Index.cshtml
@{
    if (ChackAdmin.Chack)
    {
        Layout = "_layoutAdmin";

        ViewData["title"] = @ViewBag.Container.Data.HeadingMenu[2];
    }
  
}


<link rel="stylesheet" href="~/General/libs/accordion/accordion.min.css"/>
<link rel="stylesheet" href="~/Services/css/Style2.css"/>


<section class="services section" id="services">
    <div class="container">
        <h2 class="services__titel titel-lvl-two">
            Что мы&nbsp;можем сделать
        </h2>
        <ul class="services__list accordion-list list-reset">
            @foreach (var item in ViewBag.Services.ServicesPage)
            {
                <li class="services__list__item accordion">
                    <button class="services__button accordion__trigger button-reset">
                        <svg class="arrow-bottom" viewBox="0 0 9 14">
                            <path class="svg-arrow"
                                  d="M6.660,8.922 L6.660,8.922 L2.350,13.408 L0.503,11.486 L4.813,7.000 L0.503,2.515 L2.350,0.592 L8.507,7.000 L6.660,8.922 Z" />
                        </svg>
                        <span class="services__span">
                            @item.Data.Title
                        </span>
                    </button>
                    <div class="servisec__panel accordion__panel">
                        <p class="services__panel__text">
                            @item.Data.Description
                        </p>
                    </div>
                </li>
            }
        </ul>
    </div>
</section>

@if (ChackAdmin.Chack)
{
    <section class="moving-update">
        <div class="container">
            <a asp-controller="Services" asp-action="Change" class="button-moving-update  link-btn button-reset">
                Редактировать
            </a>
        </div>
    </section>
}

<script src="~/General/libs/accordion/accordion.min.js"></script>
<script src="~/Services/js/script.js"></script>